name = "cloudflare-docker-proxy"
compatibility_date = "2023-12-01"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"

[env.production]
name = "cloudflare-docker-proxy"
 routes = [
   { pattern = "docker.yountraveler.top", custom_domain = true },
   { pattern = "quay.yountraveler.top", custom_domain = true },
   { pattern = "gcr.yountraveler.top", custom_domain = true },
   { pattern = "k8s-gcr.yountraveler.top", custom_domain = true },
   { pattern = "k8s.yountraveler.top", custom_domain = true },
   { pattern = "ghcr.yountraveler.top", custom_domain = true },
   { pattern = "cloudsmith.yountraveler.top", custom_domain = true },
 ]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""

[env.staging]
name = "cloudflare-docker-proxy-staging"
 route = { pattern = "docker-staging.yountraveler.top", custom_domain = true }

[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = ""
